### ISSUE TITLE
PON gCNV resources

### ISSUE THREAD

**Issue by samkleeman1** [cphgeno/CNVbench#1]
Hi, 

Many thanks for making this available. I was wondering if you are able to provide the PON resource files e.g. the contig ploidy priors for the GATK cCNV calling.

`resources/hg19/PoN/gCNV/20190414_WES`

Kind regards,

Sam Kleeamn

**Comment by fobinf** [comment]
Dear Sam, 
I am sorry that it is not possible for us for to share a PoN in the form we are currently using it, due to legal reasons. We are working on an aggregated and summarised version, void of low frequencies, that could maybe share in the future. 

Thank you for your interest in our work.

Best regards, 
Frederik

**Comment by samkleeman1** [comment]
Many thanks for the rapid response. Please can you share the contig ploidy priors at least?
