### ISSUE TITLE
PoN in gCNV

### ISSUE THREAD

**Issue by oghzzang** [cphgeno/CNVbench#2]
Dear @fobinf

Hi, I'm Oh. 

Many thanks for this great system. 

Then, I have two questions. 

**Q1.** 
In your tool and preprint (bjiorxiv., 2021), your team use PoN in gCNV calling. 
However, there was no PoN making step in GATK best practices. 
https://github.com/broadinstitute/gatk/blob/master/scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
https://github.com/broadinstitute/gatk/blob/master/scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl

Or, the PON you are talking about is the output of the cohort mode? 
What do you think?

**Q2.** (If PON means cohort mode is correct)

Can you make a model with COHORT MODE by putting all your WGS-derived hdf5 (or tsv) files (n=70) and execute CASE mode n times to get the final CNV result? 

Many Thanks. 

Oh.

**Comment by fobinf** [comment]
Dear Oh, 

We don't really cover PoN in the manuscript, and for sure not gCNV, but found it important to mention, because we (after these investigations) found that this helped us a lot - so we would not keep this information to ourselves. 

We are currently using svdb https://github.com/J35P312/SVDB to store our PoN, and soft filter our results. I hope this will help you to get started.

Best, 
Frederik
